---
title: "About the Monitoring Area"
author: "Magali Blanco"
date: ' `r Sys.time()` '
output:
  html_document:
    df_print: paged
    toc: yes
    toc_depth: '3'
    number_sections: true
    toc_float: true
    collapsed: false
    smooth_scroll: false
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, 
                      cache=F, cache.comments = F, 
                      message = F, warning = F, 
                      tidy.opts=list(width.cutoff=60), tidy=TRUE,
                      fig.height = 5, fig.width = 8
                      )  

# # Clear workspace of all objects and unload all extra (non-base) packages
# rm(list = ls(all = TRUE))
# if (!is.null(sessionInfo()$otherPkgs)) {
#   res <- suppressWarnings(
#     lapply(paste('package:', names(sessionInfo()$otherPkgs), sep=""),
#       detach, character.only=TRUE, unload=TRUE, force=TRUE))
# }

pacman::p_load(knitr, kableExtra, 
               ggpubr, tidyverse,
               # for kaya - mapping
               ggmap, sf, #mapping
               ggspatial, #mapping, adding scales, N arrows...
               units #convert between e.g., m to km
               )    
 

set.seed(1)

```

# upload data 

### ---> ? how to convert route file w/ many segments into individual routes?

###--> delete aqs file w/ only 6 sites?


```{r}
gis_path0 <- file.path("~", "Documents", "School", "PhD", "Dissertation", "GIS", "Shapefiles") 
gis_path <- file.path("..",  "GIS", "Shapefiles") 
data_path <- file.path("~", "Documents", "School", "PhD", "Dissertation", "TRAP R Project", "Data")

project_crs <- 4326  #lat/long
m_crs <- 32148 #meters


#point locations

act0 <- readRDS(file = file.path(data_path, "Aim 2", "Geocovariates", "cov_act_preprocessed.rda"))

#add stop & route number crosswalk
route_num <- read.csv(file.path(data_path, "Aim 2", "Mobile Monitoring", "locations_190715.csv")) %>%
  mutate(Route = substr(route,str_length(route), str_length(route))) %>%
  select(native_id = site_id, Route)

mm <- readRDS(file.path(data_path, "Aim 2", "Geocovariates", "cov_mm_preprocessed.rda")) %>%
  # drop pop90, pop_ ( & ??NDVI)
  select(-contains(c("pop90_", "pop_"))) %>%
  #drop Roosevelt garage & stop w/ 1 obeservation that was replaced by MS0601
  filter(!site_id %in% c("MS0000", "MS0398")) %>%
  mutate(
    Kind = factor(ifelse(grepl("MS", native_id), "Monitoring Stop", "AQS Colocation"), 
                  levels = c("Monitoring Stop", "AQS Colocation") 
                  )
  ) %>%
  left_join(route_num)



drop_parameters <- c("Temperature", "Wind", "Pressure", "Relative Humidity", "Sample Flow", "Sample Volume")

aqs_all0 <- read.csv(file.path("Data", "EPA_annual_conc_by_monitor_2020.csv")) %>%
  filter(
    #only keep those in this study area
    grepl("Seattle", CBSA.Name),
    #sites that only have meteorological or sample paramters
    !grepl(paste0(drop_parameters, collapse = "|"), Parameter.Name, ignore.case = T)
    ) %>%
  mutate(
    #make new ID
    native_id = paste0(State.Code,
             str_pad(string =  County.Code,
                     width = 3, 
                     side = "left", 
                     pad = 0),
             str_pad(string =  Site.Num,
                     width = 4, 
                     side = "left", 
                     pad = 0)
             ),
  )


#all AQS sites in Seattle area
aqs_all <- aqs_all0  %>%
  distinct(native_id, #State.Code, County.Code, Site.Num, #Parameter.Name,
           Latitude, Longitude
           )

#aqs sites included in study
aqs <- readRDS(file = file.path(data_path, "Aim 2", "Geocovariates", "cov_agency_preprocessed.rda"))


# monitoring, study, area shapefiles
monitoring_area_shp <- read_sf(file.path(gis_path, "Monitoring", "monitoring_area_filled_in.shp")) %>%
  st_transform(project_crs)

study_area_shp <- read_sf(file.path(gis_path0, "Study area", "oval_around_monitoring_area.shp")) %>%
  st_transform(project_crs)

# water_shp <- read_sf(file.path(gis_path, "Other features", "Water", "DNR_Hydrography__Water_Bodies", "DNR_Hydrography__Water_Bodies.shp")) %>%
#   st_transform(project_crs)

routes_shp <- read_sf(file.path(gis_path0, "Routes 190910", "All routes.shp")) %>%
  st_transform(project_crs) %>%
  mutate(
    Route = as.factor(Route)
  )

# routes_shp <- routes_shp0 %>%
#   group_by(Route) %>%
#   st_combine(#by_feature=T
#              ) %>%	
#   st_cast('POLYGON') 



act <- act0 %>%
  #drop duplicate locations
  select(-native_id, -site_id) %>%
  distinct() %>%
  #add new IDs for unique locations
  mutate(native_id = paste0("act_",
                            str_pad(row_number(), width = 5, side = "left", pad=0)
                            )
         ) %>%
  select(native_id, everything())  

#create sf object for locations
act_shp <- act %>%
  #make sf object
  st_as_sf(., coords=c("longitude","latitude"), remove=F,
           crs=project_crs)

mm_shp <- mm %>%
  st_as_sf(., coords=c("longitude","latitude"), remove=F,
           crs=project_crs)

aqs_shp <- aqs %>%
  st_as_sf(., coords=c("longitude","latitude"), remove=F,
           crs=project_crs)

aqs_all_shp <- aqs_all %>%
  st_as_sf(., coords=c("Longitude","Latitude"), remove=F,
           crs=project_crs)



# cohort locations in monitoring and study areas
act_shp$in_monitoring_area <- st_intersects(act_shp, monitoring_area_shp, sparse = F) %>%
  apply(., 1, any)
act_shp$in_study_area <- st_intersects(act_shp, study_area_shp, sparse = F) %>%
  apply(., 1, any)

aqs_shp$in_monitoring_area <- st_intersects(aqs_shp, monitoring_area_shp, sparse = F) %>%
  apply(., 1, any)  

aqs_all_shp$in_monitoring_area <- st_intersects(aqs_all_shp, monitoring_area_shp, sparse = F) %>%
  apply(., 1, any)  


#clean/convert back to df

aqs_shp <- aqs_shp %>%
  filter(in_monitoring_area==TRUE) %>%
  select(-in_monitoring_area)

aqs <- aqs_shp %>%
  st_drop_geometry() #%>%
  # filter(in_monitoring_area==TRUE) %>%
  # select(-in_monitoring_area)

aqs_all_shp <- aqs_all_shp %>%
  filter(in_monitoring_area==TRUE) %>%
  select(-in_monitoring_area)

aqs_all <- aqs_all_shp %>%
  st_drop_geometry() #%>%
  # filter(in_monitoring_area==TRUE) %>%
  # select(-in_monitoring_area)


```

proportion of ACT locations in study and monitoring areas

```{r}

act_shp %>%
  st_drop_geometry() %>%
  group_by(in_monitoring_area) %>%
  summarize(
    n = n(),
    all_act_locations = nrow(.),
    prop = n/all_act_locations
  ) %>%
  kable(caption = "unique ACT locations in the monitoring area", 
        digits = 2) %>% 
  kable_styling()
  
```

```{r}
#only keep shapefile w/ sites inside monitoring area

act_shp <- act_shp %>%
  #only need these points
  filter(in_monitoring_area == TRUE) %>%
  select(-in_monitoring_area, -in_study_area) 
 
act <- act_shp %>%
  st_drop_geometry() #%>% 
  ##only need these points
  # filter(in_monitoring_area == TRUE) %>%
  # select(-in_monitoring_area, -in_study_area) 


```

```{r, eval=F}
#save files as shp files for easy QGIS mapping verification later

#save cohort locations 
act_shp %>%
  select(native_id, latitude, longitude) %>%
  st_write(file.path(gis_path, "ACT", paste0("unique_act_locations_", Sys.Date() , ".shp")) )

# save mobile monitoring stop locations
mm_shp %>%
  select(native_id, latitude, longitude) %>%
  #mutate(
  #   kind = ifelse(grepl("MS", native_id), "Stop", "AQS Colocation")
  # ) %>%
  st_write(file.path(gis_path, "Monitoring", paste0("mm_locations", ".shp")) )

#save all AQS sites
aqs_all_shp %>%
  select(native_id, Latitude, Longitude) %>%
  st_write(file.path(gis_path, "AQS Sites", paste0("all_aqs_sites", ".shp")), 
           #delete file if already exists
           delete_layer=TRUE )


```



# Jitter Cohort locations

add new columns for this

```{r}
#act_shp_jit

#doestn' plot anything other than the main coordinates if keep as same sf object?
act_shp_jit <- act_shp %>%
  #jitter in a meters transformation
  st_transform(m_crs) %>%
  mutate(
     long_m = st_coordinates(.)[,1],
     lat_m = st_coordinates(.)[,2],
     
     #jittered. max amount that locations should be jittered: +-200 m
     lat_jit_m = jitter(lat_m, amount = 500),
     long_jit_m = jitter(long_m, amount = 500)
     ) %>% 
  #convert new meter coordinates to lat/long
  st_drop_geometry() %>%
  st_as_sf(., coords=c("long_jit_m","lat_jit_m"), remove=F,
           crs=m_crs) %>%
  #get these in lat/long (like other shapefiles - for plotting)
  st_transform(project_crs) %>%
  mutate(
    long_jit_deg = st_coordinates(.)[,1],
    lat_jit_deg = st_coordinates(.)[,2],
  ) #%>%
  #back to normal
  # st_drop_geometry() %>%
  # st_as_sf(., coords=c("longitude","latitude"), remove=F,
  #          crs=project_crs)
   
  

  


```


# Distance between monitoring and cohort locations

AQS sites are all the ones in the monitoring area (n=9)


```{r}
#calculate distance from cohort locations to monitors
# example: https://dominicroye.github.io/en/2020/geographic-distance/

dist_aqs <- st_distance(act_shp, aqs_all_shp) %>%
  #set_units(km) %>%
   as.data.frame()

dist_mm <- st_distance(act_shp, mm_shp) %>%
  #set_units(km) %>%
   as.data.frame()

#find monitor w/ shortest distance
pos_aqs <- apply(dist_aqs, 1, which.min)
pos_mm <- apply(dist_mm, 1, which.min)
#calculate shortest distance (meters)
min_dist_aqs <- apply(dist_aqs, 1, min)
min_dist_mm <- apply(dist_mm, 1, min)


act_shp <- act_shp %>%
  mutate(
    #nearest_monitor_type = all_monitoring$monitoring[pos],
    nearest_aqs_monitor = aqs_all_shp$native_id[pos_aqs],
    nearest_aqs_lat = aqs_all_shp$latitude[pos_aqs],
    nearest_aqs_long = aqs_all_shp$longitude[pos_aqs],
    
    nearest_mm_monitor = mm_shp$native_id[pos_mm],
    nearest_mm_lat = mm_shp$latitude[pos_mm],
    nearest_mm_long = mm_shp$longitude[pos_mm],
    
    dist_aqs_monitor = min_dist_aqs,
    dist_mm_monitor = min_dist_mm

  )


act_shp %>%
  st_drop_geometry() %>% 
  gather("Monitor", "distance", dist_aqs_monitor, dist_mm_monitor) %>% 
  mutate(Monitor = ifelse(grepl("aqs", Monitor), "AQS", "Mobile")) %>%  
  
  group_by(Monitor) %>%
  summarize(
    ACT_N = n(),
    Min = min(distance),
    Q05 = quantile (distance, 0.05),
    Mean = mean(distance),
    Sd = sd(distance),
    Q95 = quantile (distance, 0.95),
    Max = max(distance)
  ) %>%
  kable(caption = "distance (m) from AQS (n=6) and mobile stop (n=309) monitoring locations to ACT cohort locations in the monitoring area", 
        digits = 0
        ) %>%
  kable_styling()
  
```


# Map


```{r}
# create background map for grid/mapping
#bbox <- st_bbox(act_shp)

#make box little bigger than monitoring area
bbox <- st_bbox(st_transform(st_buffer(st_transform(act_shp, m_crs), 10000), project_crs ))

names(bbox) <- c("left", "bottom", "right", "top")

# # make a bit wider
# wider <- (max(act_shp$longitude) - min(act_shp$longitude))*0.03
# bbox[1] <- bbox[1] - wider
# #this side is wider for some reason
# bbox[3] <- bbox[3] + wider*.5

# background map
map0 <- suppressMessages(get_stamenmap(bbox = bbox, 
                                      zoom = 11,
                                      #maptype = "toner" #"toner-lite"
                                      maptype = "terrain" 
                                      )
                         ) %>%
  # Make basic map image from the tiles
  ggmap(ggmap = ., darken = c(0.5, "white")) + theme_void()

## usage example: 
# map0 + geom_point()
```

```{r}
#test - make monitoring area slightly larger. Issue b/c of water

test <-  st_transform(
  st_buffer( st_transform(monitoring_area_shp, m_crs), 1000),
 project_crs 
)

```


```{r, fig.height=10}
map0 + 
  #monitoring area
  geom_sf(data = monitoring_area_shp, 
          #data = test, # monitoring_area_shp, 
                aes(fill = "Monitoring Area"), 
          inherit.aes = F,

          #reduce/eliminate outline
          lwd = 0.1, #0, 
          alpha = 0.1,
           ) + 
  
  #jittered ACT locations
  geom_point(data = act_shp_jit, 
                aes(
                  shape="ACT Cohort",
                    y=lat_jit_deg,
                    x=long_jit_deg
                    ),
              
          inherit.aes = F,
          alpha=0.2,
          size=0.5,
          #shape=5
           ) +
  

  #route lines
  geom_sf(data=routes_shp,
        aes(col = Route
            ),
        #col = routes_shp$Route,
        inherit.aes = F,
        #linetype="dashed",
        alpha=0.7
        ) +
  
  #monitoring stops
  geom_sf(data = mm_shp, 
          aes(col = Route,  
              #shape="Stop"
              ),
          inherit.aes = F,
          size=2  
           ) + 
  #colocations
  geom_sf(data = filter(mm_shp, Kind == "AQS Colocation"), 
          aes(#col = Route, #"Mobile Monitoring",
              shape= "AQS Colocation",
              ),
          inherit.aes = F,
          size=3 
           ) + 
  
    # # add scale & N arrow to top
  geom_sf(data = monitoring_area_shp, inherit.aes = FALSE,
          #don't actually the polygon our outline
          alpha=0, lwd = 0) +
    annotation_scale(data = monitoring_area_shp, location = "tl") +
    annotation_north_arrow(location = "tl",
                           #point towards North Pole
                           which_north = "true",
                           pad_y = unit(0.5, "in"),
                           style = north_arrow_fancy_orienteering
                           ) +

  theme_bw() +
  
  theme(
      legend.justification=c(1,1), #(0,1)
      legend.position=c(1,1),#(0,1)
      legend.background =  element_blank()
      ) + 
  
  scale_shape_manual(values = c(2,1 #,21
                                )) +
  
  #order how legend items are presented
  guides(col = guide_legend(order = 2),
         shape = guide_legend(order = 3), 
         fill = guide_legend(order = 1)
         
         ) +
  
    labs( 
         x = "Longitude",
         y = "Latitude",
         fill = "",
         col = "Monitoring\nRoute",
         shape = "",  
         caption = ""
         ) 



#ggsave(file.path("..", "Manuscript", "Images", "f1_map.jpg"), width = 7.5, height = 10)

```

# Density Plots


```{r}
# covars <- c("log_m_to_a1", #"log_m_to_a123", 
#             "log_m_to_l_airp", #"log_m_to_airp", 
#             "log_m_to_rr", "pop10_s01000", "elev_elevation")

covars <- c("log_m_to_a1", "log_m_to_a1_a2_intersect",  
            "log_m_to_l_airp",
            "log_m_to_ry", 
            "log_m_to_l_port",
            "log_m_to_coast"
            )

mm_act <- mm_shp %>%
  select(covars) %>%
  mutate(Kind = "Mobile Monitoring") %>%
  rbind(mutate(select(act_shp, covars), Kind = "ACT Cohort")) %>%
  st_drop_geometry()

mm_act %>%
  gather("Covariate", "Value", -Kind) %>%
  mutate(
    Covariate = recode_factor(factor(Covariate),
                              "log_m_to_a1" = "Log Meters to A1 Road", 
                              "log_m_to_a1_a2_intersect" = "Log Meters to A1-A2 Intersection",
                              "log_m_to_l_airp" = "Log Meters to Large Airport",
                              "log_m_to_ry" = "Log Meters to Railyard",
                              "log_m_to_l_port" = "Log Meters to Large Port",
                              "log_m_to_coast" = "Log Meters to Coast"
                              #  "elev_elevation" = "Elevation (m)",
                              # "log_m_to_a1" = "Log Meters to A1 Road",
                              # "log_m_to_a123"  = "Log Meters to A1, A2 or A3 Road",
                              #  "log_m_to_l_airp" = "Log Meters to Large Airport",
                              # "log_m_to_rr" = "Log Meters to Railroad",
                              # "pop10_s01000" = "Population Within a 1 km Radius"
                               )
    
  ) %>%
  
  ggplot(aes(x=Value, fill=Kind)) + 
  facet_wrap(~Covariate, scales="free") + 
  geom_density(alpha=0.3) + 
  
  theme(legend.position = "bottom") +
  
  labs(fill = "Location")
   
ggsave(file.path("..", "Manuscript", "Images", "density_plots.jpg"), width = 10, height = 8)

```


# Route Satistics


```{r}
# mm, mm_shp

 
# mm %>%
#   group_by(Route) %>%
#   summarize(
#     stops = length(unique(native_id))
#   )

```



