---
title: "PCA of annual average pollutant concentrations at stop monitoring locations"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, 
                      cache=F, cache.comments = F, 
                      message = F, warning = F, 
                      tidy.opts=list(width.cutoff=60), tidy=TRUE,
                      fig.height = 6, fig.width = 10
                      )  

```


```{r}
# Clear workspace of all objects and unload all extra (non-base) packages
rm(list = ls(all = TRUE))
if (!is.null(sessionInfo()$otherPkgs)) {
  res <- suppressWarnings(
    lapply(paste('package:', names(sessionInfo()$otherPkgs), sep=""),
           detach, character.only=TRUE, unload=TRUE, force=TRUE))
}

pacman::p_load(kableExtra,
               tidyverse,
               #pls, gstat, #variogram()
               sf,
               pls, ggbiplot#, #PCA plots
               #parallel
               )

#use_cores <- 4

set.seed(1)

#functions
#source("0_Functions.R")

image_path <- file.path("..", "Manuscript", "Images", "Temp", "PCA")

###########################################################################################
# UPLOAD DATA
###########################################################################################
# mapping variables
lat_long_crs <- 4326

```

```{r, echo=T}
# predictions to consider
keep_averages <- c("median_of_means")
keep_polluants <- c("pnc_noscreen", "ma200_ir_bc1", "no2", "pm2.5_ug_m3", "co2_umol_mol")

```

```{r}
# full dataset: 309 site estimates and geocovariates
annual <- readRDS(file.path("Data", "Output", "annual.rda")) %>%
  #only want these averages & pollutants
  filter(annual %in% keep_averages,
         variable %in% keep_polluants
         ) %>%
  #select(location, latitude, longitude, variable, value) %>%
  spread(variable, value)

#shapefiles
monitoring_area <- readRDS(file.path("Data", "Output", "GIS", "monitoring_land_shp.rda"))  

###########################################################################################
# PCA
###########################################################################################

pca1 <- prcomp(annual[keep_polluants], center = T, scale. = T , #rank. = 2
               )

# add the values of each sample in terms of the principal components
annual <- cbind(annual, pca1$x)

#prop of variance explained
summary(pca1)

###########################################################################################

#The relationship (correlation or anticorrelation, etc) between the initial variables and the principal components
pca_rotation <- pca1$rotation %>%
  as.data.frame( ) %>%  
  rownames_to_column() %>%
  arrange(desc(abs(PC1)))

pca_rotation %>%
  kable(caption = "PCA pollutant rotation: the correlation between each pollutant and the principal component.") %>%
  kable_styling()  

#plot
ggbiplot(pca1, #labels=round(exp(annual$log_m_to_rr)/1000),
         #plot different PC components
         #choices=c(2,3)
         )

ggsave(file.path(image_path, "pc_plot.png"), width = 6, height = 6)

```

```{r, fig.height=10}
###########################################################################################
# MAP
###########################################################################################

ggplot() +
  geom_sf(data=monitoring_area) + 
  geom_point(data=gather(annual, "pc", "pc_value", PC1:PC3), aes(x=longitude, y=latitude, col=pc_value)) + 
  facet_wrap(~pc) +
  scale_color_gradient2()

ggsave(file.path(image_path, "pca_map.png"), width = 6, height = 6)



```

